DROP TABLE admin CASCADE CONSTRAINTS PURGE;

DROP TABLE BENEFIT CASCADE CONSTRAINTS PURGE;

DROP TABLE certification CASCADE CONSTRAINTS PURGE;

DROP TABLE district CASCADE CONSTRAINTS PURGE;

DROP TABLE employee CASCADE CONSTRAINTS PURGE;

DROP TABLE OT_PAY CASCADE CONSTRAINTS PURGE;

DROP TABLE other_emp CASCADE CONSTRAINTS PURGE;

DROP TABLE PAB_ITEM CASCADE CONSTRAINTS PURGE;

DROP TABLE PAB_LINEITEM CASCADE CONSTRAINTS PURGE;

DROP TABLE REG_PAY CASCADE CONSTRAINTS PURGE;

DROP TABLE teacher CASCADE CONSTRAINTS PURGE;

DROP TABLE teacher_cert_int CASCADE CONSTRAINTS PURGE;

DROP TABLE TOTAL_PAB CASCADE CONSTRAINTS PURGE;


/* I suggest to create the table EMPLOYEE first.  You should create the table 
first with NO foreign keys.  There are two foreign keys that should be added in 
using ALTER TABLE after all tables are created.  This is because the tables all 
reference each other in a way that you must remove the foreign keys temporarily
so that the tables can be created.  

If you take my suggestion above and place your CREATE TABLE statements in this
script in the same order as the place marked below, you should not run into 
problems with foreign keys restricting the creation of your tables.  You can 
include the other table's FKs in the single CREATE TABLE statements without 
problem if you implement in the correct order.

Do not forget to add those FK's to the employee table at the end.
*/

--CREATE TABLE EMPLOYEE();


CREATE TABLE EMPLOYEE (
DISTRICT_ID CHAR(5) NOT NULL,
EMP_ID CHAR(5) NOT NULL,
EMP_FNAME CHAR (50)  NULL,
EMP_LNAME CHAR (50) NOT NULL,
ZIPCODE CHAR(5) NULL,
HIREDATE DATE  DEFAULT sysdate NULL,
PREVIOUS_EXPERIENCE_YEARS NUMBER(3,1) DEFAULT '0' NULL ,
HIGHEST_EARNED_DEGREE CHAR(11) DEFAULT 'Bachelors' NULL ,
DIRECT_ADMIN_ID CHAR(5) NULL,
IS_ADMIN CHAR(1) DEFAULT 'N' NOT NULL ,
IS_TEACHER CHAR(1) DEFAULT 'Y' NOT NULL ,
EDU_EMAIL VARCHAR(20) NOT NULL,

CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMP_ID),
CONSTRAINT EMPLOYEE_UK UNIQUE (EDU_EMAIL),
CONSTRAINT EMPLOYEE_EDU_EMAIL CHECK (UPPER(EDU_EMAIL) LIKE '%__@__%.EDU'),
CONSTRAINT EMPLOYEE_HIGHEST_EARNED_DEGREE_CHK CHECK (HIGHEST_EARNED_DEGREE IN ('GRE', 'High School', 'Associate', 'Bachelor', 'Master', 'Doctorate')),
CONSTRAINT EMP_HIREDATE_CHK CHECK (HIREDATE >= TO_DATE('1950-01-01', 'YYYY-MM-DD'))
);


--CREATE TABLE ADMIN();

CREATE TABLE ADMIN(
A_EMP_ID CHAR(5) NOT NULL,
ADMIN_START_DATE DATE DEFAULT sysdate NOT NULL,
ADMIN_END_DATE DATE NULL,
DIVERSITY_TRAINING_CERT CHAR(1) DEFAULT 'N' NOT NULL,
ADMIN_TITLE CHAR(40) NULL,

CONSTRAINT ADMIN_PK PRIMARY KEY(A_EMP_ID),
CONSTRAINT ADMIN_FK FOREIGN KEY(A_EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
CONSTRAINT ADMIN_DIVERSITY_CERT_CHECK CHECK (DIVERSITY_TRAINING_CERT IN ('Y', 'N')),
CONSTRAINT ADMIN_END_DATE_CHECK CHECK (ADMIN_END_DATE >= ADMIN_START_DATE OR ADMIN_END_DATE IS NULL)
);


--CREATE TABLE TEACHER();

CREATE TABLE TEACHER(
T_EMP_ID CHAR(5) NOT NULL,
IS_FULLTIME CHAR(1) DEFAULT 'Y' NOT NULL,
GRADE_OR_SPECIAL CHAR(1) DEFAULT 'G' NOT NULL,
CONSTRAINT TEACHER_PK PRIMARY KEY (T_EMP_ID),

CONSTRAINT TEACHER_FK FOREIGN KEY (T_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
CONSTRAINT TEACHER_GRADE_OR_SPECIAL_CHK CHECK (GRADE_OR_SPECIAL IN ('G', 'S'))
);

--CREATE TABLE OTHER_EMP();

CREATE TABLE OTHER_EMP(
O_EMP_ID CHAR(5) NOT NULL,
TYPE CHAR(30) NOT NULL,
TITLE CHAR(50) NULL,

CONSTRAINT OTHER_EMP_PK PRIMARY KEY (O_EMP_ID),
CONSTRAINT OTHER_EMP_FK FOREIGN KEY (O_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
CONSTRAINT OTHER_EMP_TYPE_CHK CHECK (TYPE IN ('CUSTODIAL', 'SECURITY', 'COUNSELING', 'CONTRACT', 'LANDSCAPING', 'UNCATEGORIZED'))
);

--CREATE TABLE CERTIFICATION();

CREATE TABLE CERTIFICATION(
CERT_ID CHAR(5) NOT NULL,
STATE_CERT_CODE CHAR(10) NOT NULL,
CERT_DESC VARCHAR2(100) NULL,

CONSTRAINT CERTIFICATION_PK PRIMARY KEY(CERT_ID),
CONSTRAINT CERTIFICATION_UK UNIQUE (STATE_CERT_CODE)
);

--CREATE TABLE TEACHER_CERT_INT();


CREATE TABLE TEACHER_CERT_INT(
T_EMP_ID CHAR(5) NOT NULL,
CERT_ID CHAR(5) NOT NULL,
DATE_EFFECTIVE DATE NOT NULL,
DATE_EXPIRES DATE,

CONSTRAINT TEACHER_CERT_INT_PK PRIMARY KEY (T_EMP_ID, CERT_ID, DATE_EFFECTIVE),
CONSTRAINT TEACHER_CERT_INT_FK1 FOREIGN KEY (T_EMP_ID) REFERENCES TEACHER (T_EMP_ID),
CONSTRAINT TEACHER_CERT_INT_FK2 FOREIGN KEY (CERT_ID) REFERENCES CERTIFICATION (CERT_ID)
);

--CREATE TABLE DISTRICT();

CREATE TABLE DISTRICT(
DISTRICT_ID CHAR(5) NOT NULL,
DISTRICT_NAME VARCHAR2(100) NOT NULL,
SUPERINTENDENT_ID CHAR(5),

CONSTRAINT DISTRICT_PK PRIMARY KEY (DISTRICT_ID),
CONSTRAINT DISTRICT_UK UNIQUE (SUPERINTENDENT_ID),
CONSTRAINT DISTRICT_FK FOREIGN KEY (SUPERINTENDENT_ID) REFERENCES ADMIN (A_EMP_ID)
);

/* The following provIDed table definitions will run AFTER you have created at 
least the Employee and Admin tables correctly and implemented in your account 
*/

CREATE TABLE TOTAL_PAB (
    EMP_ID          CHAR(5) NOT NULL,
    TAX_YEAR       NUMBER(4, 0) NOT NULL,
    REG_PAY         NUMBER(7, 0) NULL,
    OVERTIME_PAY    NUMBER(7, 0) NULL,
    OTHER_PAY       NUMBER(7, 0) NULL,
    TOTAL_BENEFITS  NUMBER(7, 0) NULL,
    DATE_LAST_CALC  DATE NULL,
    PAB_ID          CHAR(5) NOT NULL,
    REVIEW_ADMIN_ID CHAR(5) NULL,

    CONSTRAINT TOTAL_PAB_UK UNIQUE ( EMP_ID, tax_year ),
    CONSTRAINT TOTAL_PAB_PK PRIMARY KEY ( PAB_ID ),
    CONSTRAINT TOTAL_PAB_FK1 FOREIGN KEY ( EMP_ID ) REFERENCES EMPLOYEE ( EMP_ID ),
    CONSTRAINT TOTAL_PAB_FK2 FOREIGN KEY ( REVIEW_ADMIN_ID ) REFERENCES ADMIN ( A_EMP_ID )
);


CREATE TABLE PAB_ITEM (
    PAB_ITEM_ID CHAR(5) NOT NULL,
    TYPE        CHAR(15) NOT NULL,
    ITEM_DESC   VARCHAR2(100) NOT NULL,

    CONSTRAINT PAB_ITEM_PK PRIMARY KEY ( PAB_ITEM_ID ),
    CONSTRAINT PAB_ITEM_TYPE_CHK CHECK ( TYPE IN ( 'REGULAR PAY', 'OVERTIME PAY', 'OTHER PAY', 'BENEFIT' ) )
);

CREATE TABLE BENEFIT (
    PAB_ITEM_ID     CHAR(5) NOT NULL,
    TAXABLE_CODE_ID CHAR(10) NOT NULL,

    CONSTRAINT BENEFIT_PK PRIMARY KEY ( PAB_ITEM_ID ),
    CONSTRAINT BENEFIT_FK FOREIGN KEY ( PAB_ITEM_ID )
        REFERENCES PAB_ITEM ( PAB_ITEM_ID )
);

CREATE TABLE OT_PAY (
    PAB_ITEM_ID        CHAR(5) NOT NULL,
    HOLIDAY_MULTIPLIER NUMBER(4, 2) NOT NULL,

    CONSTRAINT OT_PAY_PK PRIMARY KEY ( PAB_ITEM_ID ),
    CONSTRAINT OT_PAY_FK FOREIGN KEY ( PAB_ITEM_ID )
        REFERENCES PAB_ITEM ( PAB_ITEM_ID ),
    CONSTRAINT OT_PAY_HOLIDAY_MULTIPLIER_CHK CHECK ( HOLIDAY_MULTIPLIER BETWEEN ( 1.00 ) AND ( 3.50 ) )
);

CREATE TABLE REG_PAY (
    PAB_ITEM_ID                CHAR(5) NOT NULL,
    collective_bargaining_sect CHAR(15) NOT NULL,
    CONSTRAINT REG_PAY_PK PRIMARY KEY ( PAB_ITEM_ID ),
    CONSTRAINT REG_PAY_FK FOREIGN KEY ( PAB_ITEM_ID )
        REFERENCES PAB_ITEM ( PAB_ITEM_ID )
);

CREATE TABLE PAB_LINEITEM (
    PAB_ID           CHAR(5) NOT NULL,
    PAB_ITEM_ID      CHAR(5) NOT NULL,
    BEG_DATE         DATE NOT NULL,
    END_DATE         DATE NOT NULL,
    amount_posted    NUMBER(9, 2) DEFAULT 0 NOT NULL,
    posted_timestamp TIMESTAMP(6) DEFAULT sysdate NOT NULL,
    CONSTRAINT PAB_LINEITEM_PK PRIMARY KEY ( PAB_ITEM_ID,
                                             PAB_ID,
                                             BEG_DATE,
                                             END_DATE ),
    CONSTRAINT PAB_LINEITEM_FK FOREIGN KEY ( PAB_ID )
        REFERENCES TOTAL_PAB ( PAB_ID ),
    CONSTRAINT PAB_LINEITEM_FK1 FOREIGN KEY ( PAB_ITEM_ID )
        REFERENCES PAB_ITEM ( PAB_ITEM_ID )
);

/* This is where to put the ALTER TABLE for employee table and any other 
constraints that you want to add with ALTER (check constraints would be 
most likely).  The statements below are incomplete and need to be finished
IF you dID not put the FKs in the CREATE TABLE statement for the employee table
(as suggested) CONSTRAINT EMPLOYEE_EMAIL_CHK CHECK (REGEXP_LIKE(UPPER(EDU_EMAIL), '^[^@]{2,}@[^@]{2,}\.EDU$')).*/


ALTER TABLE employee
    ADD CONSTRAINT EMPLOYEE_FK FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICT(DISTRICT_ID);

ALTER TABLE employee
    ADD CONSTRAINT EMPLOYEE_FK1 FOREIGN KEY (DIRECT_ADMIN_ID) REFERENCES ADMIN(A_EMP_ID);